/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EnergyRouteImport } from './routes/energy'
import { Route as MaintenanceRouteImport } from './routes/maintenance'
import { Route as ProductionRouteImport } from './routes/production'
import { Route as QualityRouteImport } from './routes/quality'
import { Route as SafetyRouteImport } from './routes/safety'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnergyRoute = EnergyRouteImport.update({
  id: '/energy',
  path: '/energy',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceRoute = MaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductionRoute = ProductionRouteImport.update({
  id: '/production',
  path: '/production',
  getParentRoute: () => rootRouteImport,
} as any)
const QualityRoute = QualityRouteImport.update({
  id: '/quality',
  path: '/quality',
  getParentRoute: () => rootRouteImport,
} as any)
const SafetyRoute = SafetyRouteImport.update({
  id: '/safety',
  path: '/safety',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/energy': typeof EnergyRoute
  '/maintenance': typeof MaintenanceRoute
  '/production': typeof ProductionRoute
  '/quality': typeof QualityRoute
  '/safety': typeof SafetyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/energy': typeof EnergyRoute
  '/maintenance': typeof MaintenanceRoute
  '/production': typeof ProductionRoute
  '/quality': typeof QualityRoute
  '/safety': typeof SafetyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/energy': typeof EnergyRoute
  '/maintenance': typeof MaintenanceRoute
  '/production': typeof ProductionRoute
  '/quality': typeof QualityRoute
  '/safety': typeof SafetyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/energy' | '/maintenance' | '/production' | '/quality' | '/safety'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/energy' | '/maintenance' | '/production' | '/quality' | '/safety'
  id:
    | '__root__'
    | '/'
    | '/energy'
    | '/maintenance'
    | '/production'
    | '/quality'
    | '/safety'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EnergyRoute: typeof EnergyRoute
  MaintenanceRoute: typeof MaintenanceRoute
  ProductionRoute: typeof ProductionRoute
  QualityRoute: typeof QualityRoute
  SafetyRoute: typeof SafetyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/energy': {
      id: '/energy'
      path: '/energy'
      fullPath: '/energy'
      preLoaderRoute: typeof EnergyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance': {
      id: '/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof MaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/production': {
      id: '/production'
      path: '/production'
      fullPath: '/production'
      preLoaderRoute: typeof ProductionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quality': {
      id: '/quality'
      path: '/quality'
      fullPath: '/quality'
      preLoaderRoute: typeof QualityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safety': {
      id: '/safety'
      path: '/safety'
      fullPath: '/safety'
      preLoaderRoute: typeof SafetyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EnergyRoute: EnergyRoute,
  MaintenanceRoute: MaintenanceRoute,
  ProductionRoute: ProductionRoute,
  QualityRoute: QualityRoute,
  SafetyRoute: SafetyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
